steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/crop-inference/crop-inference:latest
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/crop-inference/crop-inference:latest
