services:
  flask-app:
    image: gcr.io/vinovoltaics-webapp/weather-microservice-image # to be deployed via GitHub action
  database:
    image: mongo
    volumes:
      - database-volume:/data/db

volumes:
  database-volume: