services:
  grafana:
    image: grafana/grafana:7.5.17
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./localhost.key
        target: /etc/grafana/localhost.key
      - type: bind
        source: ./localhost.crt
        target: /etc/grafana/localhost.crt
volumes:
  grafana-volume: