name: Deployment

on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: agrivoltaics-flutter-firebase
  AR_REPO: app-images

  AR_HOST: us-east4-docker.pkg.dev
  AR_BASE: us-east4-docker.pkg.dev/agrivoltaics-flutter-firebase/app-images

  RUN_REGION: us-east4

jobs:
  #
  # Flutter web application
  #
  app-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: "access_token"

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AR_HOST }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AR_BASE }}/vinovoltaics-webapp-image:latest
          cache-from: type=registry,ref=${{ env.AR_BASE }}/vinovoltaics-webapp-image:cache
          cache-to: type=registry,ref=${{ env.AR_BASE }}/vinovoltaics-webapp-image:cache,mode=max
          file: ./application/agrivoltaics_flutter_app/Dockerfile
          context: ./application/agrivoltaics_flutter_app
          build-args: |
            INFLUXDB_URL=${{ vars.INFLUXDB_URL }}
            INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }}
            INFLUXDB_ORG=${{ vars.INFLUXDB_ORG }}
            INFLUXDB_BUCKET=${{ vars.INFLUXDB_BUCKET }}
            INFLUXDB_DEBUG=${{ vars.INFLUXDB_DEBUG }}
            AUTHORIZED_EMAILS=${{ vars.AUTHORIZED_EMAILS }}

  app-deploy-cloud-run:
    needs: app-build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Deploy Cloud Run Service (Flutter project)
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service: vinovoltaics-webapp
          image: ${{ env.AR_BASE }}/vinovoltaics-webapp-image:latest
          region: ${{ env.RUN_REGION }}