name: Deployment

on: 
  push:
    branches:
    - "deploy"

jobs:
  build-and-publish-docker:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ GITHUB_WORKSPACE }}/application/agrivoltaics_flutter_app
          push: true
          tags: vinovoltaics-webapp
          # labels: ${{ steps.meta.outputs.labels }}

#   deploy-gcp-cloud-run:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: 'read'
#       id-token: 'write'

#     steps:
#     - uses: 'actions/checkout@v3'

# #     - uses: 'google-github-actions/auth@v1'
# #       with:
# #         workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
# #         service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

#     - uses: 'google-github-actions/auth@v1'
#       with:
#         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#     - id: 'deploy'
#       uses: 'google-github-actions/deploy-cloudrun@v1'
#       with:
#         service: 'vinovoltaics-webapp'
#         image: 'gcr.io/cloudrun/hello'

#     - name: 'Use output'
#       run: 'curl "${{ steps.deploy.outputs.url }}"'
